### PR TITLE
feat: use sessionStorage to save state of filters

### LINKED ISSUE #288: Route the 'back' button when viewing a project to the last viewed group of projects
Question about the way the ‘back’ button interacts with pagination on the portal. I was noticing on the NC site that if I’m on pg. 2 of the projects list and click into a project, hitting the ‘back’ button takes me to pg. 1 (instead of the pg I was on). Is that standard practice, or would it be possible to be redirected back to the page immediately prior? 

This is related to https://github.com/thepolicylab/example-project-portal/issues/272 which has to do with the sort order.
A decision was made earlier on to avoid including filters, sorting and the page number in the URL, but that means that this "back" functionality is a bit weird. We might want to revisit that decision.

from https://github.com/thepolicylab/example-project-portal/issues/271

### PR DESCRIPTION
**Pull request by jashlu**

### CODE REVIEW

**Review by hollandjg — COMMENTED** [review]
This works with the filters! Nice. 

How easy would it be to include the results page number in here, so when you hit back it loads the page you were just on? 

If it's easy, we could add that, if not let's make that into a separate Issue (and write down anything we know about the problem, any pitfalls we'd need to solve) and hand it over to the new keepers of the portal.

**Comment by jashlu** [comment]
> This works with the filters! Nice.
> 
> How easy would it be to include the results page number in here, so when you hit back it loads the page you were just on?
> 
> If it's easy, we could add that, if not let's make that into a separate Issue (and write down anything we know about the problem, any pitfalls we'd need to solve) and hand it over to the new keepers of the portal.

Hey John, thanks for the review/comments. So this is what Heather and I have been trying to tackle recently. To summarize quickly, it's hard for us to differentiate when a projectPage is being loaded because of 

1. pressing the back button and wanting to reload the state of filters/sorting, which may include different page number
2. filters/sorting applied to the project page so we want to show a fresh set of projects, starting on page 1.

This is because of the use of useEffect hooks and useState variables. I think, as you suggest, it may be better to exclude storing page in the session in this PR and get this merged in. I can put in another issue documenting the challenge with adding page number. Again, thanks for taking a look!

**Comment by hollandjg** [comment]
> I can put in another issue documenting the challenge with adding page number.

That sounds great. Thanks, Josh!

**Review by hollandjg — CHANGES_REQUESTED** [review]
This seems to me well organized and thought through. Seems to work too. Thanks!

One last thing – it looks like your reformatter didn't run: 
Screenshot 2024-01-19 at 13 54 53

The line breaks are a little wonky. Maybe rerun that (you might need to reconfigure your IDE) and then it should be good to go!

**Review by hollandjg — APPROVED** [review]
I reran prettier locally – I think yours was configured differently. Looks good now!

**Comment by jashlu** [comment]
> I reran prettier locally – I think yours was configured differently. Looks good now!

Thank you! Merging this in.

**Pull request merged**
