### PR TITLE
fix!: upgrade to Decap-CMS

### PR DESCRIPTION
**Pull request by hollandjg**
The Decap-CMS team have released a new plugin for Gatsby with the newest version of Decap-CMS (formerly Netlify-CMS).

Resolves:
- #275

### CODE REVIEW

**Comment by hollandjg** [comment]
Preview site with this package and the example-content repo: **https://deploy-preview-137--qn-project-portal-preview.netlify.app/**
(looks to be working)

**Review by jashlu — CHANGES_REQUESTED** [review]
Screenshot 2023-11-29 at 11 31 16 AM

Was taking a look at the updated UI and noticed some of the dates were unclickable. Seems like they have deprecated the `date` widget for Decap. 

https://decapcms.org/docs/widgets/#datetime

I think we will have to change it to `datetime` like how it is for `date posted`

**Comment by hollandjg** [comment]
> Screenshot 2023-11-29 at 11 31 16 AM
> Was taking a look at the updated UI and noticed some of the dates were unclickable. Seems like they have deprecated the `date` widget for Decap.
> 
> https://decapcms.org/docs/widgets/#datetime
> 
> I think we will have to change it to `datetime` like how it is for `date posted`
> 
> Besides that, everything else looks great! thanks John🙏

Looks like someone didn't test his PR properly. 🫣

**Comment by hollandjg** [comment]
Hey @jashlu – I've pushed an update. Does this work better now?

**Comment by jashlu** [comment]
Looks great!

**Pull request merged**
