### PR TITLE
refactor: split page layout component into two functions, simplifying testing

### PR DESCRIPTION
**Pull request by hollandjg**
Prepare for handover to RENCI: split page layout components into two parts:
- **new** `components/PageLayout` – this handles all of the styling and has a simple interface which doesn't "know" anything about the graphQL schema
- `layouts/Layout` – this handles the gatsby-specific graphQL bits, and uses `components/PageLayout` for the actual rendering

Additional simplifications:
- Move navbar config into the staticText block of the siteMetadata, to be consistent with the other staticText pieces

Drive-by-improvements, required for testing of the updated components:
- Make components associated with Layout accept nulls and empty values for all of their arguments. This is required to allow the PageLayout to accept null arguments. This fixes the `defaults` site, which up until now had not reliably rendered anything in `develop` mode on some browsers (Safari, for instance).
- Add more tests with empty and null values

### CODE REVIEW

**Review by hetd54 — COMMENTED** [review]
Note for Navbar: if logo doesn't exist, the site title is no longer aligned with the page links
Do we need both Page Layout and Layout?

!! For the Page Layout, the small window still shows the logo, so I don't think this is working as expected

!! For the Project Team, the contact pictures aren't showing up in the XL window

!! For the Page Layout, the small window still shows the logo, so I don't think this is working as expected

**Comment by jashlu** [comment]
> Note for Navbar: if logo doesn't exist, the site title is no longer aligned with the page links Do we need both Page Layout and Layout?
> 
> !! For the Page Layout, the small window still shows the logo, so I don't think this is working as expected
> 
> !! For the Project Team, the contact pictures aren't showing up in the XL window
> 
> !! For the Page Layout, the small window still shows the logo, so I don't think this is working as expected

`Note for Navbar: if logo doesn't exist, the site title is no longer aligned with the page links
Do we need both Page Layout and Layout?`

Is this one question or two separate questions? I get that page layout and layout are separated so that page layout doesn't have to bear the responsibility of collecting the graphQL data. Also +1 on your first comment, we forgot to address that styling/scenario

**Comment by hollandjg** [comment]
Thanks for the feedback, @hetd54 and @jashlu ! I'll take another look at this.

**Comment by hollandjg** [comment]
> Note for Navbar: if logo doesn't exist, the site title is no longer aligned with the page links
Screenshot 2023-10-31 at 15 42 00

- [ ] Fix alignment if image is missing

**Comment by hollandjg** [comment]
> Do we need both Page Layout and Layout?

Good question. I'll see if I can convince you.

The `layouts/Layout` handles the graphql bit and converts the `data { site { siteMetadata { staticText { navBar, bottomBanner, footer } } } }` into  `{ navBar, bottomBanner, footer }`. 

Having that simpler format means that testing the PageLayout is much simpler – the stories have really simple arguments in comparison to the `layouts/Layout` stories. 

It also means that the `components/PageLayout` doesn't care at all about the graphql and the structure of the data, making it a bit simpler. 

Is that enough to make it a worthwhile abstraction for you, or is it just a pain?

**Comment by hollandjg** [comment]
> !! For the Page Layout, the small window still shows the logo, so I don't think this is working as expected

I think this is where you mean: 
Screenshot 2023-10-31 at 15 51 01

Is this the correct behavior? I think I'm missing something.

**Comment by hollandjg** [comment]
> !! For the Project Team, the contact pictures aren't showing up in the XL window

Did you mean the XS? Because this is what I'm seeing:
Screenshot 2023-10-31 at 15 53 44

This looks like a bug unrelated to the changes I made. This applies to the `Contact` component for XS screen sizes.
Screenshot 2023-10-31 at 15 56 14

**Comment by hollandjg** [comment]
> We may want to revisit the styling for the SiteTitle, which is bundled with the expand navbar icon in the smaller screens. Also it may be hard to get it aligned with the page links, because the page links are `slightly` off-center, caused by the underline that could show up under each link

Part of this might be to merge the Navbar into a single component – makes it easier to format. I've done that here: #679

**Comment by hetd54** [comment]
> > Do we need both Page Layout and Layout?
> 
> Good question. I'll see if I can convince you.
> 
> The `layouts/Layout` handles the graphql bit and converts the `data { site { siteMetadata { staticText { navBar, bottomBanner, footer } } } }` into `{ navBar, bottomBanner, footer }`.
> 
> Having that simpler format means that testing the PageLayout is much simpler – the stories have really simple arguments in comparison to the `layouts/Layout` stories.
> 
> It also means that the `components/PageLayout` doesn't care at all about the graphql and the structure of the data, making it a bit simpler.
> 
> Is that enough to make it a worthwhile abstraction for you, or is it just a pain?

Yep, I'm convinced!

**Comment by hetd54** [comment]
> > !! For the Project Team, the contact pictures aren't showing up in the XL window
> 
> Did you mean the XS? Because this is what I'm seeing: Screenshot 2023-10-31 at 15 53 44
> 
> This looks like a feature unrelated to the changes I made. This applies to the `Contact` component for XS screen sizes. Screenshot 2023-10-31 at 15 56 14
> 
> ... and it arises because by default the images are hidden (`hidden` on 30) Screenshot 2023-10-31 at 15 59 17

Nope, for some reason it wasn't showing on XL screens, but it's fine now? Maybe storybook just had a hiccup.

**Review by hetd54 — APPROVED** [review]
Beautiful!! Thanks for fixing some old style things too <3

**Pull request merged**
